### ISSUE TITLE
Warning: Undefined array key 1 in C:\Users\redhe\OneDrive\Desktop\PM4Converter\pm4converter.php on line 259

### ISSUE THREAD

**Issue by xMqneyBagz** [HimmelKreis4865/pm4converter#13]
![image](https://user-images.githubusercontent.com/113796292/207464056-cb3ca74e-448a-4c75-9019-39584db9e53c.png)

**Comment by HimmelKreis4865** [comment]
This means the folder does not exist, please refer to the tutorial (if its still relevant..)
