### ISSUE TITLE
I think a YouTube tutorial is necessary because there are like me who don't even know how to use it xd 

### ISSUE THREAD

**Issue by ZnightmcXD** [HimmelKreis4865/pm4converter#3]
youtube walkthrough

**Comment by HimmelKreis4865** [comment]
would a more detailed description also solve this?

**Comment by TheMicCraft** [comment]
I think that would be helpful.

**Comment by HimmelKreis4865** [comment]
Is this issue resolved now or is that still not precise enough?

**Comment by rac14** [comment]
He needs a tutorial on how to use this and update a pm3 plugin to pm4 tutorial on how to use this

**Comment by HimmelKreis4865** [comment]
yeah it's explained in the README now, or is this still not enough?

**Comment by rac14** [comment]
> yeah it's explained in the README now, or is this still not enough?

It's good but maybe some still didn't understand or having some problems, btw could you give me your discord account name and tag i want to talk to about some stuffs regarding this if you are with it.

**Comment by HimmelKreis4865** [comment]
HimmelKreis4865#8075
dm's are open. :)
