### ISSUE TITLE
Undefined str_ends_with

### ISSUE THREAD

**Issue by AraaCuteUwU** [HimmelKreis4865/pm4converter#5]
# php convert.php sw
Copying folder structure...
Loading plugin...
Repairing plugin files  (0/23)Call to undefined function str_ends_with()

**Comment by HimmelKreis4865** [comment]
Run this script with a php version that is at least 8.0

**Comment by AraaCuteUwU** [comment]
Already use php 8.0

**Comment by HimmelKreis4865** [comment]
If that is true, your binary is corrupted, but I don't think so. Run `php -v` (or replace php with a relative path to the binary if you used another one to execute the script)
