### ISSUE TITLE
Call to undefined function yaml_parse_file()

### ISSUE THREAD

**Issue by AraaCuteUwU** [HimmelKreis4865/pm4converter#6]
root@Araa:~/convert# php convert.php MultiVersion
Copying folder structure...
Loading plugin...
Repairing plugin files (60/60)
Found 0 possible remaining bugs that cannot be fixed with this converter (they might be invalid):                                                                                   Repairing plugin.yml...
Call to undefined function yaml_parse_file()
root@Araa:~/convert#

**Comment by HimmelKreis4865** [comment]
you need a not corrupted php8 binary with JSON extension for this script. There is no other reason causing this problem.
