### ISSUE TITLE
How do i use?

### ISSUE THREAD

**Issue by FoxyBoars23** [HimmelKreis4865/pm4converter#8]
The steps given by you is not sufficient for peoples like me can give me a proper tutorial in dc discord? My tag ⚡Ｒｉｓｈａｖ†ᴍɢ⚡#1691

**Comment by ItsToxicGG** [comment]
hello @FoxyBoars23, ill make a tutorial on youtube.

**Comment by HimmelKreis4865** [comment]
@ItsToxicGG  you made one? if yes, you can send the link right here

**Comment by ItsToxicGG** [comment]
not yet but ill do it

**Comment by Satyarth9914** [comment]
Your channel link @ItsToxicGG

**Comment by SomOp302** [comment]
> 

Did you made video
