### ISSUE TITLE
please tell in simple words 

### ISSUE THREAD

**Issue by Satyarth9914** [HimmelKreis4865/pm4converter#9]
i can't understand the process can anyone tell me in simple words.

**Comment by Aufgecodet** [comment]
Download PHP and execute the file pm4converter.php, behind it comes the location of the folder where your plugins are inside that should be converted. Now a new folder will be created there 
is the converted code inside. Hope I could help you :)

**Comment by Satyarth9914** [comment]
If you upload a tutorial on YouTube or give a video it could help me better 🙂.
